apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfl-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfl-service
  template:
    metadata:
      labels:
        app: nfl-service
    spec:
      containers:
      - name: nfl-service
        image: gopalwalia2025/my-python-service:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nfl-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: nfl-service